Update podspec to Swift 5 and min deployment target to iOS 12
scalefocus/TwoWayBondage pull request #5
Opened 2021-08-31 13:09 UTC by ODimitrovSF

- Update podspec to Swift 5 and min deployment target to iOS 12
- Update podspec version to 2.2.0

2021-08-31 13:32 UTC, plamenzhl approved these changes

2021-08-31 13:34 UTC, plamenzhl requested changes
The requirement section of the README file should also be updated to reflect the minimum iOS and Swift versions

2021-08-31 13:39 UTC, plamenzhl approved these changes

2021-08-31 14:05 UTC, kostadinzamanov approved these changes

2021-09-01 13:06 UTC, dvp-petrov approved these changes

2021-09-01 13:06 UTC, merged